version: '3.8'

services:
  db:
    image: mysql:9.2.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/ecommerce
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
